services:
  database:
    image: postgres:15-alpine
    container_name: khidma-db
    environment:
      POSTGRES_DB: khidma-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        user: www-data
        uid: 1000
    container_name: khidma-php
    volumes:
      - ./khidma-back:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: khidma-nginx
    ports:
      - "8080:80"
    volumes:
      - ./khidma-back:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  frontend:
    build:
      context: ./khidma-front
      dockerfile: Dockerfile
    container_name: khidma-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./khidma-front:/app
      - /app/node_modules

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    ports:
      - "3000:80"

volumes:
  database_data: