api_platform:
    title: 'Khidma API'
    version: '1.0.0'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    openapi:
        contact:
            name: Team API
            url: https://www.khidma.com
            email: contact@khidma.com
        swagger_ui_extra_configuration:
            docExpansion: 'none'
            persistAuthorization: true